export const metadata = {
    title: process.env.NEXT_PUBLIC_APP_NAME,
    description: 'Generated by create next app',
  }
  
  export default function AuthLayout({ children }) {
    return (
      <div>
        {children}
      </div>)
  }